package datos;

// Generated 13-feb-2014 0:31:32 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Piezas generated by hbm2java
 */
public class Piezas implements java.io.Serializable {

	private String codigo;
	private String nombre;
	private BigDecimal precio;
	private String descripcion;
	private Integer stock;
	private Set gestions = new HashSet(0);

	public Piezas() {
	}

	public Piezas(String codigo, String nombre, BigDecimal precio) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.precio = precio;
	}

	public Piezas(String codigo, String nombre, BigDecimal precio,
			String descripcion, Integer stock, Set gestions) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.precio = precio;
		this.descripcion = descripcion;
		this.stock = stock;
		this.gestions = gestions;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public Set getGestions() {
		return this.gestions;
	}

	public void setGestions(Set gestions) {
		this.gestions = gestions;
	}

}
