package datos;

// Generated 13-feb-2014 0:31:32 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Proyectos generated by hbm2java
 */
public class Proyectos implements java.io.Serializable {

	private String codigo;
	private Zonas zonas;
	private String nombre;
	private String ciudad;
	private Integer presupuesto;
	private Set gestions = new HashSet(0);

	public Proyectos() {
	}

	public Proyectos(String codigo, String nombre) {
		this.codigo = codigo;
		this.nombre = nombre;
	}

	public Proyectos(String codigo, Zonas zonas, String nombre, String ciudad,
			Integer presupuesto, Set gestions) {
		this.codigo = codigo;
		this.zonas = zonas;
		this.nombre = nombre;
		this.ciudad = ciudad;
		this.presupuesto = presupuesto;
		this.gestions = gestions;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Zonas getZonas() {
		return this.zonas;
	}

	public void setZonas(Zonas zonas) {
		this.zonas = zonas;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public Integer getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(Integer presupuesto) {
		this.presupuesto = presupuesto;
	}

	public Set getGestions() {
		return this.gestions;
	}

	public void setGestions(Set gestions) {
		this.gestions = gestions;
	}

}
